# workflow name
name: shopping_basket

# on events
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: env GOOS=windows GOARCH=amd64 go build -v ./...
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: | 
            ./*.exe
