# workflow name
name: shopping_basket

# on events
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.1.0
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: ''
            compress: 'true'
            dest: 'dist'
